version: "3"
services:
  app:
    container_name: redis-pubsub
    restart: always
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongo
      - redis
  mongo:
    container_name: mongod
    image: mongo
    ports:
      - "27017:27017"
  redis:
    container_name: rediss
    image: 'redis:4.0.11'
    ports: 
      - "6379:6379"
